//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICracker", CallbackContract=typeof(ConsoleClient.ServiceReference1.ICrackerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ICracker {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICracker/Connect")]
        void Connect();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICracker/Connect")]
        System.Threading.Tasks.Task ConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetWorkMode", ReplyAction="http://tempuri.org/ICracker/GetWorkModeResponse")]
        int GetWorkMode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetWorkMode", ReplyAction="http://tempuri.org/ICracker/GetWorkModeResponse")]
        System.Threading.Tasks.Task<int> GetWorkModeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetPasswords", ReplyAction="http://tempuri.org/ICracker/GetPasswordsResponse")]
        System.Collections.Generic.List<string> GetPasswords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetPasswords", ReplyAction="http://tempuri.org/ICracker/GetPasswordsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetPasswordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetPasswordsFile", ReplyAction="http://tempuri.org/ICracker/GetPasswordsFileResponse")]
        System.IO.Stream GetPasswordsFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetPasswordsFile", ReplyAction="http://tempuri.org/ICracker/GetPasswordsFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetPasswordsFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetPasswordsFileName", ReplyAction="http://tempuri.org/ICracker/GetPasswordsFileNameResponse")]
        string GetPasswordsFileName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetPasswordsFileName", ReplyAction="http://tempuri.org/ICracker/GetPasswordsFileNameResponse")]
        System.Threading.Tasks.Task<string> GetPasswordsFileNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICracker/SendResult")]
        void SendResult(System.Collections.Generic.Dictionary<string, string> result, System.TimeSpan elapsed);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICracker/SendResult")]
        System.Threading.Tasks.Task SendResultAsync(System.Collections.Generic.Dictionary<string, string> result, System.TimeSpan elapsed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/IsDictionaryUpToDate", ReplyAction="http://tempuri.org/ICracker/IsDictionaryUpToDateResponse")]
        bool IsDictionaryUpToDate(string md5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/IsDictionaryUpToDate", ReplyAction="http://tempuri.org/ICracker/IsDictionaryUpToDateResponse")]
        System.Threading.Tasks.Task<bool> IsDictionaryUpToDateAsync(string md5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetDictionary", ReplyAction="http://tempuri.org/ICracker/GetDictionaryResponse")]
        System.Collections.Generic.List<string> GetDictionary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetDictionary", ReplyAction="http://tempuri.org/ICracker/GetDictionaryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetDictionaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetDictionaryFile", ReplyAction="http://tempuri.org/ICracker/GetDictionaryFileResponse")]
        System.IO.Stream GetDictionaryFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetDictionaryFile", ReplyAction="http://tempuri.org/ICracker/GetDictionaryFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetDictionaryFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetDictionaryRange", ReplyAction="http://tempuri.org/ICracker/GetDictionaryRangeResponse")]
        System.Collections.Generic.Dictionary<int, int> GetDictionaryRange();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetDictionaryRange", ReplyAction="http://tempuri.org/ICracker/GetDictionaryRangeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> GetDictionaryRangeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetDictionaryFileName", ReplyAction="http://tempuri.org/ICracker/GetDictionaryFileNameResponse")]
        string GetDictionaryFileName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetDictionaryFileName", ReplyAction="http://tempuri.org/ICracker/GetDictionaryFileNameResponse")]
        System.Threading.Tasks.Task<string> GetDictionaryFileNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetBFAlphabet", ReplyAction="http://tempuri.org/ICracker/GetBFAlphabetResponse")]
        string GetBFAlphabet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetBFAlphabet", ReplyAction="http://tempuri.org/ICracker/GetBFAlphabetResponse")]
        System.Threading.Tasks.Task<string> GetBFAlphabetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetBFNextPrefix", ReplyAction="http://tempuri.org/ICracker/GetBFNextPrefixResponse")]
        string GetBFNextPrefix();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetBFNextPrefix", ReplyAction="http://tempuri.org/ICracker/GetBFNextPrefixResponse")]
        System.Threading.Tasks.Task<string> GetBFNextPrefixAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetBFGenerationRange", ReplyAction="http://tempuri.org/ICracker/GetBFGenerationRangeResponse")]
        System.Collections.Generic.Dictionary<int, int> GetBFGenerationRange();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICracker/GetBFGenerationRange", ReplyAction="http://tempuri.org/ICracker/GetBFGenerationRangeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> GetBFGenerationRangeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrackerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICracker/DisplayMessage")]
        void DisplayMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICracker/UpdatePasswordsList")]
        void UpdatePasswordsList(string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrackerChannel : ConsoleClient.ServiceReference1.ICracker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrackerClient : System.ServiceModel.DuplexClientBase<ConsoleClient.ServiceReference1.ICracker>, ConsoleClient.ServiceReference1.ICracker {
        
        public CrackerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CrackerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CrackerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CrackerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CrackerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect() {
            base.Channel.Connect();
        }
        
        public System.Threading.Tasks.Task ConnectAsync() {
            return base.Channel.ConnectAsync();
        }
        
        public int GetWorkMode() {
            return base.Channel.GetWorkMode();
        }
        
        public System.Threading.Tasks.Task<int> GetWorkModeAsync() {
            return base.Channel.GetWorkModeAsync();
        }
        
        public System.Collections.Generic.List<string> GetPasswords() {
            return base.Channel.GetPasswords();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetPasswordsAsync() {
            return base.Channel.GetPasswordsAsync();
        }
        
        public System.IO.Stream GetPasswordsFile() {
            return base.Channel.GetPasswordsFile();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetPasswordsFileAsync() {
            return base.Channel.GetPasswordsFileAsync();
        }
        
        public string GetPasswordsFileName() {
            return base.Channel.GetPasswordsFileName();
        }
        
        public System.Threading.Tasks.Task<string> GetPasswordsFileNameAsync() {
            return base.Channel.GetPasswordsFileNameAsync();
        }
        
        public void SendResult(System.Collections.Generic.Dictionary<string, string> result, System.TimeSpan elapsed) {
            base.Channel.SendResult(result, elapsed);
        }
        
        public System.Threading.Tasks.Task SendResultAsync(System.Collections.Generic.Dictionary<string, string> result, System.TimeSpan elapsed) {
            return base.Channel.SendResultAsync(result, elapsed);
        }
        
        public bool IsDictionaryUpToDate(string md5) {
            return base.Channel.IsDictionaryUpToDate(md5);
        }
        
        public System.Threading.Tasks.Task<bool> IsDictionaryUpToDateAsync(string md5) {
            return base.Channel.IsDictionaryUpToDateAsync(md5);
        }
        
        public System.Collections.Generic.List<string> GetDictionary() {
            return base.Channel.GetDictionary();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetDictionaryAsync() {
            return base.Channel.GetDictionaryAsync();
        }
        
        public System.IO.Stream GetDictionaryFile() {
            return base.Channel.GetDictionaryFile();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetDictionaryFileAsync() {
            return base.Channel.GetDictionaryFileAsync();
        }
        
        public System.Collections.Generic.Dictionary<int, int> GetDictionaryRange() {
            return base.Channel.GetDictionaryRange();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> GetDictionaryRangeAsync() {
            return base.Channel.GetDictionaryRangeAsync();
        }
        
        public string GetDictionaryFileName() {
            return base.Channel.GetDictionaryFileName();
        }
        
        public System.Threading.Tasks.Task<string> GetDictionaryFileNameAsync() {
            return base.Channel.GetDictionaryFileNameAsync();
        }
        
        public string GetBFAlphabet() {
            return base.Channel.GetBFAlphabet();
        }
        
        public System.Threading.Tasks.Task<string> GetBFAlphabetAsync() {
            return base.Channel.GetBFAlphabetAsync();
        }
        
        public string GetBFNextPrefix() {
            return base.Channel.GetBFNextPrefix();
        }
        
        public System.Threading.Tasks.Task<string> GetBFNextPrefixAsync() {
            return base.Channel.GetBFNextPrefixAsync();
        }
        
        public System.Collections.Generic.Dictionary<int, int> GetBFGenerationRange() {
            return base.Channel.GetBFGenerationRange();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> GetBFGenerationRangeAsync() {
            return base.Channel.GetBFGenerationRangeAsync();
        }
    }
}
